name: algae_env
channels:
  - defaults
dependencies:
  - keras=2.12.0
  - matplotlib=3.8.0
  - notebook=7.0.8
  - numpy=1.23.5
  - opencv=4.6.0
  - pillow=10.2.0
  - pip=23.3.1
  - python=3.11.5
  - tensorflow=2.12.0
  - pip:
    - ultralytics==8.0.196
    - roboflow==1.1.26
    - tensorflow-metal==1.1.0
    - torch==2.2.2
    - torchvision==0.17.2
    - torchaudio==2.2.2