name: algae_env
channels:
  - defaults
dependencies:
  - python=3.11.5
  - notebook=7.0.8
  - pip>=23.3.1
  - pip:
    - ultralytics==8.1.47
    - roboflow==1.1.27
    - torch==2.2.2
    - opencv-contrib-python-headless==4.9.0.80
    - supervision==0.19.0